### ISSUE TITLE
Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by Mashsquare** [kokou2kpadenou/recaptcha3-nextjs#2]
followed all the steps and the result was the following:

`Failed to compile:
./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./styles/globals.css
TypeError: Cannot read properties of undefined (reading 'config')`

**Comment by kokou2kpadenou** [comment]
I'm trying to reproduce this error but I can't. This repository uses nextjs 10, have you tried upgrading to the latest version? If you provide more details I may be able to help you.
Anyway, I would migrate to 12.
